// @ts-check
import js from "@eslint/js";
import reactHooks from "eslint-plugin-react-hooks";
import tseslint from "typescript-eslint";

export default tseslint.config(
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // next-env.d.ts is regenerated by `next dev`/`next build` and explicitly says "this file
    // should not be edited" — lint it out rather than fight its auto-managed content.
    ignores: ["node_modules/**", ".next/**", "lib/ws-types.ts", "next-env.d.ts"],
  },
  {
    rules: {
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
    },
  },
  {
    files: ["**/*.tsx", "**/*.ts"],
    plugins: { "react-hooks": reactHooks },
    rules: {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
    },
  },
  {
    // AudioWorkletGlobalScope (docs/phase-1-LEARN.md §3) — no DOM, no `window`; these globals
    // exist only inside the worklet's own realm, not in a normal browser/eslint environment.
    files: ["public/worklets/**/*.js"],
    languageOptions: {
      globals: {
        AudioWorkletProcessor: "readonly",
        registerProcessor: "readonly",
        sampleRate: "readonly",
        currentTime: "readonly",
        currentFrame: "readonly",
      },
    },
  },
  {
    // Plain Node scripts (scripts/check-design-tokens.mjs) — run via `node`, not bundled by
    // Next.js, so they get Node's globals instead of the browser ones the rest of this config
    // assumes.
    files: ["scripts/**/*.mjs"],
    languageOptions: {
      globals: {
        console: "readonly",
        process: "readonly",
        URL: "readonly",
      },
    },
  },
);
