"""Repository functions — no raw SQL at call sites (CLAUDE.md §5), only these. Every write here
is a plain insert; `turn_id`/`id` values are always generated by the caller (uuid7(), from
../core or a shared helper) before the call, never left to a server-side default, because the
same turn_id is reused across `turns`, `turn_metrics`, `latency_events` and `model_calls` and
those tables share no FK to enforce that consistency for us (docs/decisions/0002).
"""

from __future__ import annotations

import uuid as std_uuid
from datetime import UTC, datetime
from typing import Any

from sqlalchemy import insert, select, update
from sqlalchemy.ext.asyncio import AsyncSession

from ..core.config import get_settings
from ..core.ids import uuid7
from .tables import latency_events, model_calls, sessions, turn_metrics, turns


async def get_session_row(db: AsyncSession, session_id: std_uuid.UUID) -> dict[str, Any] | None:
    result = await db.execute(select(sessions).where(sessions.c.id == session_id))
    row = result.mappings().first()
    return dict(row) if row is not None else None


async def close_session(
    db: AsyncSession,
    session_id: std_uuid.UUID,
    *,
    end_reason: str,
    duration_ms: int,
    recording_key: str | None = None,
    recording_format: str | None = None,
    peaks: list[float] | None = None,
) -> None:
    """Task 1.1/3.3a: "mark the session `closed` with `end_reason`", plus (new in Phase 3) the
    recording/peaks metadata the report player needs. Without the status update, a finalised
    runtime's session row stays `status="created"` forever, which silently eats one slot of
    every future `max_concurrent_sessions` check for that user. The recording fields are only
    ever set here, once, at the same moment the session is marked closed — nothing else in this
    codebase writes them."""
    now = datetime.now(UTC)
    values: dict[str, Any] = {
        "status": "closed",
        "end_reason": end_reason,
        "ended_at": now,
        "duration_ms": duration_ms,
        "updated_at": now,
    }
    if recording_key is not None:
        values["recording_key"] = recording_key
    if recording_format is not None:
        values["recording_format"] = recording_format
    if peaks is not None:
        values["peaks"] = peaks
    await db.execute(update(sessions).where(sessions.c.id == session_id).values(**values))
    await db.commit()


async def insert_turn(
    db: AsyncSession,
    *,
    turn_id: std_uuid.UUID,
    session_id: std_uuid.UUID,
    index: int,
    speaker: str,
    text: str,
    start_ms: int,
    end_ms: int,
    word_timings: list[dict[str, Any]],
    truncated: bool,
    asr_confidence: float | None,
) -> None:
    now = datetime.now(UTC)
    await db.execute(
        insert(turns).values(
            id=turn_id,
            created_at=now,
            updated_at=now,
            session_id=session_id,
            index=index,
            speaker=speaker,
            text=text,
            start_ms=start_ms,
            end_ms=end_ms,
            word_timings=word_timings,
            truncated=truncated,
            asr_confidence=asr_confidence,
            training_excluded=False,
        )
    )
    await db.commit()


async def insert_turn_metrics(
    db: AsyncSession,
    *,
    metrics_id: std_uuid.UUID,
    session_id: std_uuid.UUID,
    turn_id: std_uuid.UUID,
    wpm: float,
    filler_count: int,
    filler_rate: float,
    longest_pause_ms: int,
    speech_ratio: float,
    word_count: int,
) -> None:
    now = datetime.now(UTC)
    await db.execute(
        insert(turn_metrics).values(
            id=metrics_id,
            created_at=now,
            updated_at=now,
            session_id=session_id,
            turn_id=turn_id,
            wpm=wpm,
            filler_count=filler_count,
            filler_rate=filler_rate,
            longest_pause_ms=longest_pause_ms,
            speech_ratio=speech_ratio,
            word_count=word_count,
        )
    )
    await db.commit()


async def insert_latency_events(db: AsyncSession, rows: list[dict[str, Any]]) -> None:
    """Bulk insert — the batched latency writer's flush path. A no-op on an empty batch so the
    periodic flush timer doesn't touch the DB on a quiet connection."""
    if not rows:
        return
    now = datetime.now(UTC)
    host_class = get_settings().host_class
    prepared = [
        {"id": uuid7(), "host_class": host_class, **row, "created_at": now, "updated_at": now}
        for row in rows
    ]
    await db.execute(insert(latency_events), prepared)
    await db.commit()


async def insert_model_call(
    db: AsyncSession,
    *,
    call_id: std_uuid.UUID,
    session_id: std_uuid.UUID,
    turn_id: std_uuid.UUID | None,
    role: str,
    model: str,
    prompt_version: str | None,
    tokens_in: int,
    tokens_out: int,
    ttft_ms: float | None,
    total_latency_ms: float,
    cost_cents: float,
    cached: bool,
) -> None:
    now = datetime.now(UTC)
    await db.execute(
        insert(model_calls).values(
            id=call_id,
            created_at=now,
            updated_at=now,
            session_id=session_id,
            turn_id=turn_id,
            role=role,
            model=model,
            prompt_version=prompt_version,
            tokens_in=tokens_in,
            tokens_out=tokens_out,
            ttft_ms=ttft_ms,
            total_latency_ms=total_latency_ms,
            cost_cents=cost_cents,
            cached=cached,
        )
    )
    await db.commit()
