"""initial schema

HAND-REVIEWED, not blind autogenerate — see docs/phase-0-BUILD.md TASK 0.4 acceptance
criteria. Autogenerate produced the 15 `op.create_table` calls (including, correctly, the
`turns` composite PK and `postgresql_partition_by`); everything else in this file — extension
creation, the pgvector column, the actual monthly partitions and a DEFAULT catch-all — was
added by hand because autogenerate cannot express any of it from a diff against empty models.
See docs/decisions/0002-turns-partitioning-and-fk.md for why child tables reference
`sessions.id` rather than a composite FK into `turns`.

Revision ID: a06824b506ad
Revises:
Create Date: 2026-08-20 02:16:26.059524
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op
from dateutil.relativedelta import relativedelta
from sqlalchemy.dialects import postgresql

revision: str = 'a06824b506ad'
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def _create_month_partition(table: str, year: int, month: int) -> None:
    """CREATE TABLE IF NOT EXISTS <table>_YYYY_MM PARTITION OF <table> FOR VALUES FROM (...) TO (...).
    Mirrored in scripts/create_turn_partitions.py, which extends this out over time — this
    migration only guarantees the current and next month exist (docs/phase-0-BUILD.md 0.4).
    """
    start = datetime(year, month, 1, tzinfo=UTC)
    end = start + relativedelta(months=1)
    partition_name = f"{table}_{year:04d}_{month:02d}"
    op.execute(
        f"CREATE TABLE IF NOT EXISTS {partition_name} PARTITION OF {table} "
        f"FOR VALUES FROM ('{start.date().isoformat()}') TO ('{end.date().isoformat()}')"
    )


def upgrade() -> None:
    # Defensive: the compose postgres container's init script (scripts/db/init-extensions.sql)
    # already does this, but managed Postgres (Neon) never runs that file — see
    # docs/01-SETUP-GUIDE.md §2.4. `make migrate` alone must be sufficient everywhere.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('archetype', sa.Text(), nullable=False),
    sa.Column('temperament', sa.Text(), nullable=False),
    sa.Column('voice_id', sa.Text(), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("archetype IN ('interviewer', 'hiring_manager', 'recruiter', 'examiner', 'skeptic')", name='ck_personas_archetype'),
    sa.CheckConstraint("temperament IN ('warm', 'neutral', 'blunt', 'adversarial')", name='ck_personas_temperament'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_slug'), 'personas', ['slug'], unique=True)
    op.create_table('rubrics',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rubrics_slug'), 'rubrics', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('github_id', sa.Text(), nullable=True),
    sa.Column('google_id', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('resume_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_role', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('resume_text IS NULL OR length(resume_text) > 0', name='ck_profiles_resume_not_blank'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('rubric_criteria',
    sa.Column('rubric_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('anchor_descriptors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(anchor_descriptors) = 'object' AND anchor_descriptors ?& array['1','2','3','4','5']", name='ck_rubric_criteria_anchor_descriptors_complete'),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rubric_id', 'key', name='uq_rubric_criteria_rubric_key')
    )
    op.create_table('scenarios',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('family', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('opening_strategy', sa.Text(), nullable=False),
    sa.Column('difficulty_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=True),
    sa.Column('rubric_id', sa.UUID(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("difficulty IN ('gentle', 'standard', 'hard')", name='ck_scenarios_difficulty'),
    sa.CheckConstraint("family IN ('technical', 'behavioural', 'negotiation', 'viva')", name='ck_scenarios_family'),
    sa.CheckConstraint('length(brief) >= 200', name='ck_scenarios_brief_min_length'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_difficulty'), 'scenarios', ['difficulty'], unique=False)
    op.create_index(op.f('ix_scenarios_family'), 'scenarios', ['family'], unique=False)
    op.create_index(op.f('ix_scenarios_slug'), 'scenarios', ['slug'], unique=True)
    # pgvector column, added by hand (not an ORM-mapped column yet — no query path uses it
    # until embeddings actually land). The ivfflat index is deliberately NOT created here; see
    # the "Indexes required" table in docs/phase-0-BUILD.md TASK 0.4 — building it against an
    # all-NULL column is useless and pgvector recommends building it after data exists.
    op.execute("ALTER TABLE scenarios ADD COLUMN embedding vector(384)")
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('end_reason', sa.Text(), nullable=True),
    sa.Column('target_minutes', sa.Integer(), nullable=False),
    sa.Column('focus_areas', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('resume_text_override', sa.Text(), nullable=True),
    sa.Column('brief', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("end_reason IS NULL OR end_reason IN ('user_hangup', 'duration_reached', 'persona_concluded', 'budget_exhausted', 'distress_exit', 'error')", name='ck_sessions_end_reason'),
    sa.CheckConstraint("status IN ('created', 'active', 'closing', 'closed', 'failed')", name='ck_sessions_status'),
    sa.CheckConstraint('target_minutes IN (5, 10, 20, 30)', name='ck_sessions_target_minutes'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('annotations',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_id', sa.UUID(), nullable=False),
    sa.Column('annotator_id', sa.UUID(), nullable=False),
    sa.Column('criterion_key', sa.Text(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('round >= 1', name='ck_annotations_round_positive'),
    sa.CheckConstraint('score BETWEEN 1 AND 5', name='ck_annotations_score_range'),
    sa.ForeignKeyConstraint(['annotator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turn_id', 'annotator_id', 'criterion_key', 'round', name='uq_annotations_turn_annotator_criterion_round')
    )
    op.create_index('ix_annotations_turn_criterion', 'annotations', ['turn_id', 'criterion_key'], unique=False)
    op.create_table('latency_events',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stage IN ('endpoint_detect', 'asr_finalize', 'prompt_assemble', 'model_ttft', 'first_chunk_assemble', 'tts_first_chunk', 'transport', 'e2e')", name='ck_latency_events_stage'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_latency_events_session_turn', 'latency_events', ['session_id', 'turn_id'], unique=False)
    op.create_index('ix_latency_events_stage_created_at', 'latency_events', ['stage', 'created_at'], unique=False)
    op.create_table('model_calls',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('ttft_ms', sa.Float(), nullable=True),
    sa.Column('total_latency_ms', sa.Float(), nullable=False),
    sa.Column('cost_cents', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('persona', 'endpointer', 'narrator', 'planner', 'judge', 'embedder')", name='ck_model_calls_role'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_calls_session_created_at', 'model_calls', ['session_id', 'created_at'], unique=False)
    op.create_table('reports',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('strengths', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('growth_areas', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('narrator_model_version', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'ready', 'failed')", name='ck_reports_status'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('session_scores',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('criterion_key', sa.Text(), nullable=False),
    sa.Column('aggregate_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_turn_ids', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('aggregate_score IS NULL OR aggregate_score BETWEEN 1 AND 5', name='ck_session_scores_score_range'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_session_scores_confidence_range'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'criterion_key', name='uq_session_scores_session_criterion')
    )
    op.create_table('turn_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_id', sa.UUID(), nullable=False),
    sa.Column('wpm', sa.Float(), nullable=False),
    sa.Column('filler_count', sa.Integer(), nullable=False),
    sa.Column('filler_rate', sa.Float(), nullable=False),
    sa.Column('longest_pause_ms', sa.Integer(), nullable=False),
    sa.Column('speech_ratio', sa.Float(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turn_id', name='uq_turn_metrics_turn_id')
    )
    op.create_table('turn_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_id', sa.UUID(), nullable=False),
    sa.Column('criterion_key', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_spans', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_turn_scores_confidence_range'),
    sa.CheckConstraint('score IS NULL OR score BETWEEN 1 AND 5', name='ck_turn_scores_score_range'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turn_id', 'criterion_key', name='uq_turn_scores_turn_criterion')
    )
    op.create_table('turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('word_timings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('asr_confidence', sa.Float(), nullable=True),
    sa.CheckConstraint("speaker IN ('user', 'persona')", name='ck_turns_speaker'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'created_at'),
    sa.UniqueConstraint('session_id', 'index', 'created_at', name='uq_turns_session_index_created_at'),
    postgresql_partition_by='RANGE (created_at)'
    )
    # ### end Alembic commands ###

    # Hand-added: turns is partitioned by month (docs/phase-0-BUILD.md TASK 0.4). A freshly
    # PARTITION BY'd table has no partitions at all — every insert would fail with "no
    # partition found" until at least one exists. Create the current and next month now;
    # scripts/create_turn_partitions.py keeps this rolling forward after deploy.
    now = datetime.now(UTC)
    _create_month_partition("turns", now.year, now.month)
    next_month = now + relativedelta(months=1)
    _create_month_partition("turns", next_month.year, next_month.month)
    # Safety net: catches any row outside the explicit monthly ranges (clock skew, a deploy
    # gap longer than the lookahead) instead of a hard insert failure. Should stay empty in
    # normal operation — scripts/create_turn_partitions.py is what's meant to keep up.
    op.execute("CREATE TABLE IF NOT EXISTS turns_default PARTITION OF turns DEFAULT")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # DROP TABLE on a partitioned parent cascades to every partition (turns_default, the
    # monthly ones) automatically — nothing extra to do for those here.
    op.drop_table('turns')
    op.drop_table('turn_scores')
    op.drop_table('turn_metrics')
    op.drop_table('session_scores')
    op.drop_table('reports')
    op.drop_index('ix_model_calls_session_created_at', table_name='model_calls')
    op.drop_table('model_calls')
    op.drop_index('ix_latency_events_stage_created_at', table_name='latency_events')
    op.drop_index('ix_latency_events_session_turn', table_name='latency_events')
    op.drop_table('latency_events')
    op.drop_index('ix_annotations_turn_criterion', table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_scenarios_slug'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_family'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_difficulty'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_table('rubric_criteria')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rubrics_slug'), table_name='rubrics')
    op.drop_table('rubrics')
    op.drop_index(op.f('ix_personas_slug'), table_name='personas')
    op.drop_table('personas')
    # ### end Alembic commands ###
